name: checkov
on: pull_request
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Checkov
        run: |
          pip install checkov
      - name: Test with Checkov
        id: checkov
        run: |
          echo "Executing checkov command..."
          checkov -d ./terraform | tee checkov_report.md
      - name: Upload Checkov results artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: checkov-results.md
