name: security-checks
on: pull_request

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Checkov
        run: |
          pip install checkov
      - name: Checkov Scan
        id: checkov
        run: |
          checkov -d ./terraform | tee checkov_report.json
      - name: Upload Checkov report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Checkov Report
          path: checkov_report.json

  terrascan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terrascan
        run: |
          curl -L "$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
          tar zxvf terrascan.tar.gz && rm terrascan.tar.gz
          mv terrascan /usr/local/bin
      - name: Terrascan Scan
        id: terrascan
        run: |
          terrascan scan -f terraform -d ./terraform | tee terrascan_report.json
      - name: Upload Terrascan report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Terrascan Report
          path: terrascan_report.json
