name: security-checks
on: pull_request
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Checkov
        run: |
          pip install checkov
      - name: Checkov Scan
        id: checkov
        run: |
          checkov -d ./terraform | tee checkov_report.json
      - name: Upload Checkov report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Checkov Report
          path: checkov_report.json
  terrascan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terrascan
        run: |
          curl -L "$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
          tar -xzf terrascan.tar.gz
          sudo mv terrascan /usr/local/bin/
      - name: Terrascan Scan
        id: terrascan
        run: |
          terrascan scan -f ./terraform --output-json > terrascan_report.json
      - name: Upload Terrascan report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Terrascan Report
          path: terrascan_report.json
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tfsec
        run: |
          curl -L "$(curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > tfsec.tar.gz
          tar -xzf tfsec.tar.gz
          sudo mv tfsec /usr/local/bin/
      - name: tfsec Scan
        id: tfsec
        run: |
          tfsec ./terraform | tee tfsec_report.json
      - name: Upload tfsec report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tfsec Report
          path: tfsec_report.json
