name: security-checks
on: pull_request
jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        curl https://raw.githubusercontent.com/bridgecrewio/checkov/master/install_checkov.sh | bash -s v2.0.575
        
    - name: Run Checkov directory scan
      run: |
        checkov -d . -o json > checkov_output.json
        
    - name: Upload Checkov output
      uses: actions/upload-artifact@v2
      with:
        name: checkov_output
        path: checkov_output.json
