name: checkov
on: pull_request
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Checkov
        run: |
          pip install checkov
      - name: Checkov Scan
        id: checkov
        run: |
          checkov -d ./terraform --output-file checkov_report.md

      - name: Upload report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Checkov Report
          path: checkov_report.md
    terrascan:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        iac_dir: terraform
