name: security-checks
on: pull_request
jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Checkov
        run: |
          pip install checkov
      - name: Test with Checkov
        id: checkov
        run: |
          echo "Executing checkov command..."
          checkov -d ./terraform --skip-check CKV_AWS_42 --output-name checkov-results
      - name: Display results
        if: always()
        run: |
          echo "Checkov results by severity:"
          cat checkov-results | jq '.results | group_by(.metadata.severity) | map({severity: first().metadata.severity, count: length})'
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: checkov-results
