name: security-checks
on: pull_request
jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          args: --soft-fail --output json
      - name: Filter Checkov results by severity
        run: python3 filter_checkov_results.py
      - name: Upload Checkov output
        uses: actions/upload-artifact@v2
        with:
          name: checkov-output
          path: checkov_output.txt
