name: security-checks
on: pull_request
jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        run: |
          echo "Executing checkov command..."
          checkov -d ./terraform --skip-check CKV_AWS_42
      - name: Upload Checkov Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: output.txt
      - name: Debug Checkov Results
        if: always()
        run: |
          echo "Checking if output.txt exists..."
          ls
          cat output.txt
