name: Checkov Scan
on: pull_request
jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0
    - name: Initialize Terraform
      run: terraform init ./terraform
      working-directory: ${{ github.workspace }}
    - name: Install Checkov
      run: |
        curl -LJO https://github.com/bridgecrewio/checkov/releases/latest/download/checkov-linux-arm64
        sudo mv checkov-linux-arm64 /usr/local/bin/checkov
        sudo chmod +x /usr/local/bin/checkov
    - name: Run Checkov
      run: |
        checkov -d ./terraform > checkov_output.txt
      working-directory: ${{ github.workspace }}
    - name: Upload Checkov Report
      uses: actions/upload-artifact@v2
      with:
        name: Checkov Report
        path: checkov_output.txt
