name: security-checks
on: pull_request
jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Checkov
      run: |
        curl -LJO https://github.com/bridgecrewio/checkov/releases/latest/download/checkov-linux-arm64
        sudo mv checkov-linux-arm64 /usr/local/bin/checkov
        sudo chmod +x /usr/local/bin/checkov
    - name: Run Checkov
      run: |
        checkov -d . > checkov_output.txt
    - name: Upload Checkov Report
      uses: actions/upload-artifact@v2
      with:
        name: Checkov Report
        path: checkov_output.txt
