name: Checkov Scan
on: pull_request
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Checkov
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install checkov
    - name: Run Checkov
      run: |
        checkov -d ./terraform > checkov_output.txt
    - name: Upload Checkov Report
      uses: actions/upload-artifact@v2
      with:
        name: Checkov Report
        path: checkov_output.txt
