name: security-checks
on: pull_request
jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terrascan
        run: |
          curl -L "$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | jq -r '.assets[].browser_download_url' | grep 'Linux_x86_64.tar.gz$')" -o terrascan.tar.gz
          tar xvfz terrascan.tar.gz
          sudo mv terrascan /usr/local/bin/
      - name: Test with Terrascan
        id: terrascan
        run: |
          echo "Executing terrascan command..."
          terrascan scan -i terraform -f ./terraform -o docx -o-file terrascan-results.docx
      - name: Display Terrascan results
        run: |
          echo "Terrascan results:"
          terrascan parse -f docx -f-file terrascan-results.docx -o yaml
      - name: Upload Terrascan results artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: terrascan-results
          path: terrascan-results.docx
